const newsSites = {
  'news.naver.com': '#articleBodyContents',
  'v.media.daum.net': '#harmonyContainer',
  'news.chosun.com': '#news_body_id',
  'news.donga.com': '#contents .article_view .article_txt',
  'news.mt.co.kr': '#textBody',
  'news.joins.com': '#article_body',
  'www.yonhapnews.co.kr': '#articleWrap',
  'www.asiae.co.kr': '#bodyContents .txt',
  'news.mk.co.kr': '#article_body',
  'biz.heraldcorp.com': '#articleText',
  'news.sbs.co.kr': '.main_text',
  'news.hankyung.com': '#newsView',
  'news.kbs.co.kr': '#cont_newstext',
  'seoul.co.kr': '#atic_txt1',
  'news1.kr': '#articles_detail',
  'segye.com': '#article_txt',
  'news.khan.co.kr': '.art_body',
  'daily.hankooki.com': '#GS_Content',
  'imnews.imbc.com': '#news_content_1',
  'www.newsis.com': '#textBody',
  'www.ytn.co.kr': '#CmAdContent',
  'www.fnnews.com': '#article_content',
  'www.etnews.com': '#articleBody',
  'www.wowtv.co.kr': '#viewContent_3',
  'nocutnews.co.kr': '#pnlContent',
  'www.edaily.co.kr': '.article_body',
  'news.kmib.co.kr': '#articleBody',
  'news.ebs.co.kr': '#contents',
  'www.hani.co.kr': '.article-text-font-size',
  'news.jtbc.joins.com': '#articlebody',
  'www.ohmynews.com': '.at_contents'
}